//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VP_Felho.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fajl
    {
        public int id { get; set; }
        public string fajlnev { get; set; }
        public string kiterjesztes { get; set; }
        public byte[] adat { get; set; }
        public System.DateTime datum { get; set; }
        public int felhasznalo_id { get; set; }
    
        public virtual felhasznalo felhasznalo { get; set; }
    }
}
